---
title: "Максимально правдоподобная контрольная"
author: "Boris Demeshev"
date: "2 March 2015"
output:
  pdf_document:
    keep_tex: yes
lang: russian
---

Ровно 184 года назад, 2 марта 1831 года обвенчались Александр Пушкин и Наталья Гончарова


```{r, fig.width=3, fig.height=3, echo=FALSE}
# op <- par(mfrow=c(1,2)) 
library("jpeg")
library("grid")
library("gridExtra")
Natashka <- readJPEG("Natalia_Pushkina.jpg")
Sashka <- readJPEG("Pushkin_Alexander_by_Sokolov_P.jpg")
plot1 <- rasterGrob(Natashka)
plot2 <- rasterGrob(Sashka)
#theplot <- arrangeGrob(grob(plot1), grob(plot2), ncol=1)
#theplot
grid.arrange(plot2, plot1, ncol=2)
```

Задача 1. Александр Сергеевич оценил неизвестный параметр $\theta$ по 200 наблюдениям методом максимального правдоподобия и получил оценки $\hat{\theta}=10$ и $se(\hat{\theta})=1$. Наталья Николаевна хочет оценить параметр $\gamma=\theta^2$.

1. Как выглядит 95\%-ый доверительный интервал для $\theta$, полученный Александром Сергеевичем?
2. Наталья Николаевна построила 95\%-ый доверительный интервал для $\gamma$ преобразовав края доверительного интервала для $\theta$. Какой интервал она получила?
3. Помогите Наталье Николаевне получить  95\%-ый доверительный интервал для  $\gamma$ симметричный plot1 <- относительно $\hat{\theta}^2$

Задача 2. Методом максимального правдоподобия оценили логит-модель:

\[
\hat{y}^*_i=2+3x_i - 5z_i
\]

Для средних значений регрессоров, $\bar{x}=5$, $\bar{y}=7$, оцените:

1. Вероятность того, что $y_i=1$
2. Предельный эффект увеличения $x$ на единицу на вероятность того, что $y_i=1$


