---
title: "Метрика. Пересдача 22 сентября 2015."
output: pdf_document
lang: russian
header-includes: 
  - \newcommand{\e}{\varepsilon}
---

Задача 1. 

Предполагая нормальность остатков, оцените модель $y_i=\beta x_i + \e_i$ по трём наблюдениям: $x_1=0$, $x_2=1$, $x_3=2$, $y_1=0$, $y_2=1$, $y_3=4$. Найдите $\hat{\beta}$, $RSS$, $TSS$, $ESS$, $R^2$.


Задача 2.

По историческим данным начала 20-го века была оценена зависимость длины тормозного пути от скорости машины. По 50 наблюдениям была оценена регрессия: 

\[
\widehat{dist}_i=-5.25 + 0.75 speed_i
\]

Стандартные ошибки двух оцененных коэффициентов равны 2 и 0.08 соответственно.


1. Проверьте гипотезы о значимости каждого коэффициента на 5%-ом уровне значимости.

2. Постройте 95%-ый предиктивный интервал для длины тормозного пути машины ехавшей со скоростью 20 км/ч.

Подсказка: Нормальное N(0;1) распределение с вероятностью 95% лежит в пределах от -1.96 до 1.96.


Задача 3.

Винни-Пух построил логит-модель для предсказания качества мёда: $y_i=0$ означает неправильный мёд, а $y_i=1$ --- правильный. Правильность мёда зависит от разных характеристик дупла, в частности от правильности пчёл ($x_i$) и их количества ($z_i$). Оценка модели выглядит так:

\[
\Lambda(P[y_i=1]) = -0.2 + 2 x_i + 0.005 z_i
\]

Здесь $\Lambda()$ --- логистическая функция, $\Lambda(t)=e^t/(1+e^t)$.

1. Спрогнозируйте вероятность правильного мёда для дупла с сотней правильных пчёл.

2. Во сколько отличается вероятность правильного мёда для дупла с правильными и аналогичного дупла с неправильными пчёлами?

