<<"ci_block", echo=FALSE, include=FALSE>>=
k_all <- c(5, 6, 7, 8, 9)
hs2_all <- c(10, 20, 30, 40)



set.seed(var_no)
k <- sample(k_all, 1)
hs2 <- sample(hs2_all, 1)

n <- 50 + k

RSS <- (n - k) * hs2
ESS <- 100
TSS <- RSS + ESS

wrong <- RSS / (n - 2)
wrong0 <- round(wrong, 1)
@



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr1} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    В множественной регрессии с 3 регрессорами выборочная корреляция между переменной $Y$ и $\hat Y$ оказалась равна 0.8. Тогда $R^2$ будет равен

 \begin{multicols}{3} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{0.64}
      \wrongchoice{0.8}
      \wrongchoice{0.36}
      \wrongchoice{0.2}
      \wrongchoice{1}
      \wrongchoice{Не хватает данных для ответа}
   \end{choices}
  \end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr2} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    По некоему набору данных оценили регресиию. Потом выкинули одно наблюдение и оценили ту же самую регрессию по уменьшенной выборке. Что из этого НЕ могло произойти?

 \begin{multicols}{2} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{$R^2$ и $R^2_{adj}$ оба не изменились}
      \wrongchoice{$R^2$ и $R^2_{adj}$ оба выросли}
      \wrongchoice{$R^2$ и $R^2_{adj}$ оба упали}
      \wrongchoice{$R^2$ вырос и стал равен 1}
      \wrongchoice{один из коэффициентов поменял знак}
      \wrongchoice{один из коэффициентов стал незначимым}
   \end{choices}
  \end{multicols}
  \end{questionmult}
}




\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr3} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Исследовательница Алевтина изучает зависимость размера порции, $size$, в мишленовском ресторане от его звёздности, $star$ (от 1 до 3), и уровня цен, $price$. Она оценила модель вида $size_i = \beta_1 star1_i + \beta_2 star2_i + \beta_3 star3_i + \beta_4 price_i + u_i$, где $star1, star2, star3$ - дамми-переменные, равные 1 для ресторанов с соответствующим числом звезд, и 0 иначе. Алевтина считает, что размер порции никак не зависит от звездности ресторана. Какую гипотезу ей надо проверить?

 \begin{multicols}{3} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{ $H_0 : \beta_1 = \beta_2 = \beta_3$ }
      \wrongchoice{ $H_0 : \beta_1 = \beta_2 = \beta_3 = 0$ }
      \wrongchoice{ $H_0 : \beta_1 = \beta_2 = \beta_3 = 1$ }
      \wrongchoice{ $H_0 : \beta_1 = 2\beta_2 = 3\beta_3$ }
      \wrongchoice{ $H_0 : 3\beta_1 = 2\beta_2 = \beta_3$ }
      \wrongchoice{ $H_0 : \beta_2 = \beta_3 = 0$ }
   \end{choices}
  \end{multicols}
  \end{questionmult}
}




\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr4} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Исследовательница Алевтина по-прежнему изучает зависимость размера порции, $size$, в мишленовском ресторане от его звёздности, $star$ (от 1 до 3), и уровня цен, $price$. Она оценила модель вида $size_i = \beta_1 star1_i + \beta_2 star2_i + \beta_3 star3_i + \beta_4 price_i + u_i$, где $star1, star2, star3$ - дамми-переменные, равные 1 для ресторанов с соответствующим числом звезд, и 0 иначе. Алевтина считает, что у трёхзвездочных ресторанов цена должна влиять сильнее, чем у 1- и 2-звездочных (у этих категорий цена влияет одинаково). Какую модель ей надо оценить?

 %\begin{multicols}{1} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{ $size_i = \beta_1 star1_i + \beta_2 star2_i + \beta_3 star3_i + \beta_4 price_i + \beta_5 price_i star3_i + u_i$ }
      \wrongchoice{ $size_i = \beta_1 star1_i + \beta_3 star3_i + \beta_4 price_i + u_i$ }
      \wrongchoice{ $size_i = \beta_1 star1_i + \beta_2 star2_i + \beta_3 star3_i + \beta_4 price_i star3_i + u_i$ }
      \wrongchoice{ $size_i = \beta_1 star1_i + \beta_2 star2_i + \beta_3 star3_i + \beta_4 price_i + 10 price_i star3_i + u_i$ }
      \wrongchoice{ $size_i = \beta_0 + \beta_3 star3_i + \beta_4 price_i + u_i$ }
      \wrongchoice{ $size_i = \beta_0 + \beta_1 star3_i + \beta_2 price_i + \beta_3 price_i star3_i + u_i$ }
   \end{choices}
  %\end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr5} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Вася оценил модель $\ln Y_i = \beta_0 + \beta_1 X_i + \beta_2 \ln Z_i + u_i$. Какую модель для $Y_i$ он предполагал?

 \begin{multicols}{3} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{ $Y_i = e^{\beta_0 + \beta_1 X_i} Z_i^{\beta_2} e^{u_i}$ }
      \wrongchoice{ $Y_i = e^{\beta_0 + \beta_1 X_i} Z_i^{\beta_2} + e^{u_i}$ }
      \wrongchoice{ $Y_i = e^{\beta_0} X_i^{\beta_1} Z_i^{\beta_2} u_i$ }
      \wrongchoice{ $Y_i = e^{\beta_0 + \beta_1 X_i} Z_i^{\beta_2} + {u_i}$ }
      \wrongchoice{ $Y_i = \beta_0 X_i^{\beta_1} Z_i^{\beta_2} u_i$ }
      \wrongchoice{ $Y_i = e^{\beta_0} X_i^{\beta_1} Z_i^{\beta_2} e^{u_i}$ }
   \end{choices}
  \end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr6} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    В регрессии с 4 регрессорами, оцененной по 21 наблюдению, оказалось, что $TSS = 150$, $R^2 = 0.6$. Тогда $R^2_{adj}$ равен

 \begin{multicols}{3} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{ 1/2 }
      \wrongchoice{ 1/3 }
      \wrongchoice{ 1/4 }
      \wrongchoice{ 3/4 }
      \wrongchoice{ 2/5 }
      \wrongchoice{ 3/5 }
   \end{choices}
  \end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr7} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Регрессия с 3 регрессорами оценена по 100 наблюдениям. Какая из этих гипотез может быть проверена при помощи статистики, имеющей $F_{1, 96}$ распределение?

 \begin{multicols}{3} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{ $H_0: \beta_2 = 2 \beta_3$ }
      \wrongchoice{ $H_0: \beta_2 = \beta_3 = 0$ }
      \wrongchoice{ $H_0: \beta_1 < \beta_2 < \beta_3$ }
      \wrongchoice{ $H_0: \beta_2 = \beta_3 = 0$ }
      \wrongchoice{ $H_0: 0 < \beta_2 < 3$ }
      \wrongchoice{ $H_0: \beta_1 = \beta_2 = \beta_3$ }
   \end{choices}
  \end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr8} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Исследователь выполнил второй шаг в PE-тесте МакКиннона. В регрессии $\ln Y_i$ на исходные регрессоры и $Z_i = \hat Y_i - \exp(\widehat{\ln Y_i})$ коэффициент при $Z_i$ оказался незначимым. А в регрессии $Y_i$ на исходные регрессоры и $W_i = \ln \hat Y_i - \widehat{\ln Y_i}$ коэффициент при $W_i$ оказался значимым. Из результатов следует сделать вывод, что

 %\begin{multicols}{1} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{следует предпочесть логарифмическую модель}
      \wrongchoice{следует предпочесть линейную модель}
      \wrongchoice{следует предпочесть полулогарифмическую модель}
      \wrongchoice{тесты противоречат друг другу, ни одна из моделей не предпочитается}
      \wrongchoice{в исходной модели пропущен регрессор $Z_i$}
      \wrongchoice{в исходной модели пропущен регрессор $W_i$}
   \end{choices}
  %\end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr9} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Истинной является модель $Y_i = \beta_1 + \beta_2 X_i + u_i$. Глафира оценивает две регрессии: $\hat Y_i = \hb_1 + \hb_2X_i$ и  $\hat Y_i = \hat \gamma_1 + \hat \gamma_2 X_i + \hat \gamma_3 Z_i$ с помощью МНК. Известно, что $corr(X_i, Z_i) = 0.7$. Тогда $\gamma_2$

 \begin{multicols}{2} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{Нет верного ответа}
      \wrongchoice{является смещенной, но состоятельной оценкой для $\beta_2$}
      \wrongchoice{является несмещенной, но несостоятельной оценкой для $\beta_2$}
      \wrongchoice{смещена на $0.7 \hat \gamma_3$ относительно $\beta_2$}
      \wrongchoice{смещена на $0.7$ относительно $\beta_2$}
      \wrongchoice{смещена на $\hat \gamma_3$ относительно $\beta_2$}
   \end{choices}
  \end{multicols}
  \end{questionmult}
}



\element{midterm_16_retake2}{ % в фигурных скобках название группы вопросов
 %\AMCnoCompleteMulti
  \begin{questionmult}{pr10} % тип вопроса (questionmult — множественный выбор) и в фигурных — номер вопроса

    Если для регрессора используется преобразование Бокса-Кокса с параметром $\theta = 0$, а для зависимой переменной - с параметром $\lambda = 2$, то регрессионное уравнение представимо в виде

 \begin{multicols}{3} % располагаем ответы в 3 колонки
   \begin{choices} % опция [o] не рандомизирует порядок ответов
      \correctchoice{ $Y^2_i = \beta_1 + \beta_2 \ln X_i + u_i$ }
      \wrongchoice{ $Y_i = \beta_1 + \beta_2 \ln X_i + u_i$ }
      \wrongchoice{ $\ln Y_i = \beta_1 + \beta_2 \ln X_i + u_i$ }
      \wrongchoice{ $Y_i = \beta_1 + \beta_2 X_i + u_i$ }
      \wrongchoice{ $Y^2_i = \beta_1 + \beta_2 \ln X^2_i + u_i$ }
      \wrongchoice{ $Y^2_i = \beta_1 + \beta_2 X^2_i + u_i$ }
   \end{choices}
  \end{multicols}
  \end{questionmult}
}
