---
title: "Когда производных много :)"
output: html_document
lang: ru-RU
---

# Матричные и векторные производные 

С матричными производными есть две традиции обозначений. Одни записывают вектор производных в столбик, другие --- в строчку. Формулы выходят одинаковыми с точностью до транспонирования. При чтении других источников надо быть внимательным :)

Эти две традиции: denominator tradition (она же hessian tradition) и nominator tradition (она же jacobian tradition). 

Здесь используется denominator. 

Вектор $x$ --- это вектор-столбец из $\mathbb{R}^n$, а $X$ --- матрица размера $n\times k$.


По вектору:

\[
\frac{\partial Ax}{\partial x} = A'
\]

\[
\frac{\partial x'Ax}{\partial x} = (A' + A) x
\]

По матрице:

\[
\frac{\partial \det X}{\partial X} = \det X (X^{-1})'
\]





# Задачки

1. Сформулируйте целевую функцию классического МНК для модели $y=X\beta + u$. Найдите условия первого порядка с помощью дифференциирования по вектору и решите их.

2. Предположим, что $z_i$ --- это вектор характеристик индивида $i$. Скажем, в $z_i$ входят рост, вес, заработная плата за прошлый год и т.д. Внутри одного вектора $z_i$ характеристики будем считать зависимыми, а между индивидов --- независимыми. Имеются данные по $n$ индивидам, $z_1$, $z_2$, \ldots, $z_n$. С помощью метода максимального правдоподобия оцените модели 

    1. Модель А: $z_i \sim \mathcal{N}(\mu; I)$, где $I$ --- единичная матрица, а $\mu$ --- вектор неизвестных математических ожиданий.
    2. Модель B: $z_i \sim \mathcal{N}(0; C)$, где $C$ --- неизвестная ковариационная матрица.
    3. Модель С: $z_i \sim \mathcal{N}(\mu, C)$, где $\mu$ --- вектор неизвестных математических ожиданий, а $C$ --- неизвестная ковариационная матрица.
    
3. Предположим, что $z_i$ --- это вектор характеристик индивида $i$. Скажем, в $z_i$ входят рост, вес, заработная плата за прошлый год и т.д. Характеристики одного индивида будем считать зависимыми, а характеристики разных индивидов --- независимыми. Имеются данные по $n$ индивидам, $z_1$, $z_2$, \ldots, $z_n$. Часть из этих индивидов --- мальчики, $y_i=1$, а часть --- девочки, $y_i=0$. 
С помощью метода максимального правдоподобия оцените модели:

    1. Модель А: $P(y_i=1)=p$, для мальчиков $z_i \sim \mathcal{N}(\mu_1, C_1)$, для девочек $z_i \sim \mathcal{N}(\mu_0, C_0)$.
    2. Модель B: $P(y_i=1)=p$, для мальчиков $z_i \sim \mathcal{N}(\mu_1, C)$, для девочек $z_i \sim \mathcal{N}(\mu_0, C)$.
    3. Модель C: $P(y_i=1)=p$, для мальчиков $z_i \sim \mathcal{N}(\mu, C_1)$, для девочек $z_i \sim \mathcal{N}(\mu, C_0)$.
    
    
    
    
    