# Оценка популярных моделей с помощью MCMC

```{r, message=FALSE, warning=FALSE}
library(MCMCpack)
library(ggplot2)
library(GGally)
```

```{r}
h <- swiss
str(h)
```

```{r}
theme_set(theme_bw())
# plotmatrix(h)
ggpairs(h)
```

```{r}
formula <- Fertility~Agriculture+Examination+Catholic+Education
```


Обычный МНК:
```{r}
m1 <- lm(formula, data=h)
summary(m1)
```

```{r}
priors <- c(2,0.8,0.5,0.3,-5)
```


```{r}
m1.mcmc <- MCMCregress(formula,data=h,b0=priors,B0=0.0001)
summary(m1.mcmc)
```

## Что можно вытащить из результатов оценивания?

```{r}
str(m1.mcmc)
```

```{r}
beta.sample <- as.data.frame(m1.mcmc)
beta.sample$t <- 1:nrow(beta.sample) # добавим номер элемента последовательности
str(beta.sample)
```

Зададим удобные имена переменным
```{r}
colnames(beta.sample)[1] <- "const"
```

Построим апостериорное распределение свободного члена и визуально оценим сходимость:
```{r}
ggplot(beta.sample,aes(x=const))+geom_density()
qplot(t,Agriculture,data=beta.sample)
```

Оценим модель с другим априорным мнением о коэффициентах:
```{r}
priors <- c(0.2,0.1,0.2,-0.3,-0.1) 
```

```{r}
m1.mcmc <- MCMCregress(formula,data=h,b0=priors, B0=0.0001 ) 
summary(m1.mcmc)
```




