---
title: "БУКА. Памятка судьям :)"
output:
  pdf_document:
    keep_tex: yes
---


БУКА --- это Большой Устный эКонометрический прАздник. Мы создаём две составляющие --- серьёзную и праздничную. Будь требователен и добр к участникам БУКИ --- это исследовательская группа, они нам нужны. Можно агитировать писать у себя ВКР!

Чтобы праздник не затянулся слишком долго, стоит ориентироваться на максимум в 10 минут на одного участника. В списках указано ориентировочное время прибытия участников на станцию.

Оценка напротив участника --- результат письменной части экзамена. Возможный максимум за письменную часть был 7 баллов, т.е. вместо результатов 8, 9 и 10 ставилось 7. Значит, те у кого стоит 7 баллов могут быть скрытыми отличниками. 

Результат участника нужно оценивать по шкале 0, 1, 2 и 3. Здесь 0 означает "согласен с оценкой за письменную часть", 1 --- "думаю, что участнику нужно добавить еще 1 балл" и так далее. Оценка проставляется в ведомость на станции. В бегунок участника ставится забавный знак о посещении станции :)

Все могут в любое время угощаться вкусняшками!

